// Seed vocabulary. Loaded once on first run; user's own additions are stored separately in localStorage.
const SEED_CARDS = [
  // Lanthanides (57-71)
  {
    word: "Lanthanum",
    definition: "La, #57 — the element the lanthanide series is named after; soft, silvery metal.",
    context: "Lanthanum oxide improves the optical properties of camera and telescope lenses.",
    morphology: "Greek 'lanthanein' (to lie hidden) — it hid in cerium ore for years. '-um' = metal element suffix.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Cerium",
    definition: "Ce, #58 — most abundant lanthanide.",
    context: "The flint in a disposable lighter is mostly cerium alloy; cerium oxide polishes glass.",
    morphology: "Named after the asteroid Ceres (discovered 2 years earlier), itself named for the Roman goddess of agriculture.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Praseodymium",
    definition: "Pr, #59 — used in aircraft engine alloys and yellow-green glass coloring.",
    context: "Didymium glass in welding goggles contains praseodymium to filter the yellow sodium flare.",
    morphology: "Greek 'prasios' (leek-green) + 'didymos' (twin) — the green twin, split from 'didymium'.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Neodymium",
    definition: "Nd, #60 — makes the strongest permanent magnets (NdFeB).",
    context: "Neodymium magnets power headphones, hard drives, and EV motors.",
    morphology: "Greek 'neos' (new) + 'didymos' (twin) — the new twin, the other half of didymium.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Promethium",
    definition: "Pm, #61 — radioactive, no stable isotopes.",
    context: "Promethium was used in luminous watch dials and compact nuclear batteries.",
    morphology: "Named after Prometheus, the Titan who stole fire from the gods — a nod to harnessing nuclear fire.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Samarium",
    definition: "Sm, #62 — used in heat-resistant samarium-cobalt magnets.",
    context: "Samarium-153 is used in radiotherapy to relieve bone cancer pain.",
    morphology: "From the mineral samarskite, named after Russian mining engineer Colonel Samarsky — first element named after a person (indirectly).",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Europium",
    definition: "Eu, #63 — the most reactive lanthanide.",
    context: "Europium phosphors made the red in old CRT TVs and glow in euro banknotes under UV light as an anti-counterfeiting measure.",
    morphology: "Named after the continent of Europe.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Gadolinium",
    definition: "Gd, #64 — strongly paramagnetic.",
    context: "Gadolinium contrast agents make tissues light up in MRI scans.",
    morphology: "From the mineral gadolinite, named after Finnish chemist Johan Gadolin, pioneer of rare-earth research.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Terbium",
    definition: "Tb, #65 — green phosphor in displays and lighting.",
    context: "Terfenol-D, a terbium alloy, changes shape in magnetic fields and is used in precision actuators and flat-panel speakers.",
    morphology: "Named after Ytterby, a village in Sweden whose quarry yielded 4 element names: terbium, ytterbium, yttrium, erbium.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Dysprosium",
    definition: "Dy, #66 — keeps neodymium magnets working at high temperature.",
    context: "EV motor magnets are doped with dysprosium so they don't demagnetize when hot.",
    morphology: "Greek 'dysprositos' (hard to get at) — 'dys-' (bad/difficult, as in dysfunction) + 'prositos' (approachable).",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Holmium",
    definition: "Ho, #67 — highest magnetic moment of any element.",
    context: "Holmium lasers are the standard for breaking up kidney stones.",
    morphology: "From 'Holmia', Latin name for Stockholm, home city of its discoverer.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Erbium",
    definition: "Er, #68 — amplifies light at telecom wavelengths.",
    context: "Erbium-doped fiber amplifiers boost signals in undersea internet cables; erbium lasers do skin resurfacing.",
    morphology: "Another element named after Ytterby, Sweden (see terbium).",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Thulium",
    definition: "Tm, #69 — rarest naturally occurring lanthanide.",
    context: "Thulium-170 sources power portable X-ray devices where electricity isn't available.",
    morphology: "From 'Thule', the ancient Greek name for the far north / Scandinavia.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Ytterbium",
    definition: "Yb, #70 — used in atomic clocks and stress sensors.",
    context: "Ytterbium lattice clocks are accurate to within a second over the age of the universe.",
    morphology: "Third element named after Ytterby, Sweden — the quarry that keeps on giving.",
    synonyms: "",
    category: "lanthanides",
  },
  {
    word: "Lutetium",
    definition: "Lu, #71 — hardest and densest lanthanide, last in the series.",
    context: "Lutetium oxyorthosilicate crystals detect gamma rays in PET scanners.",
    morphology: "From 'Lutetia', the Roman name for Paris, home city of its discoverer.",
    synonyms: "",
    category: "lanthanides",
  },

  // General chemistry vocabulary
  {
    word: "Isotope",
    definition: "Atoms of the same element with the same number of protons but different numbers of neutrons.",
    context: "Carbon-12 and carbon-14 are isotopes; the latter's decay enables radiocarbon dating.",
    morphology: "Greek 'isos' (equal) + 'topos' (place) — occupying the same place in the periodic table.",
    synonyms: "nuclide (related, not identical)",
    category: "chemistry",
  },
  {
    word: "Valence electron",
    definition: "An electron in the outermost shell of an atom, involved in forming chemical bonds.",
    context: "Sodium has one valence electron, which it readily gives up — hence its violent reactivity.",
    morphology: "Latin 'valentia' (strength, capacity) — same root as 'valiant' and 'value'.",
    synonyms: "outer-shell electron, bonding electron",
    category: "chemistry",
  },
  {
    word: "Catalyst",
    definition: "A substance that speeds up a reaction without being consumed by it.",
    context: "The platinum in your car's catalytic converter breaks down exhaust pollutants for years without being used up.",
    morphology: "Greek 'kata-' (down) + 'lysis' (loosening) — same 'lysis' as in 'analysis' and 'hydrolysis'.",
    synonyms: "accelerant (loosely); figuratively: trigger, spark, impetus",
    category: "chemistry",
  },
  {
    word: "Moiety",
    definition: "A part or fragment of a larger molecule, usually with a distinct chemical identity.",
    context: "The sugar moiety of the antibiotic is essential for binding its target.",
    morphology: "Old French 'moitié' (half), from Latin 'medietas' (middle) — same root as 'medium' and 'mediate'.",
    synonyms: "fragment, portion, functional group (looser)",
    category: "chemistry",
  },
  {
    word: "Stoichiometry",
    definition: "The calculation of relative quantities of reactants and products in a chemical reaction.",
    context: "Stoichiometry tells you exactly how much oxygen is needed to burn a gram of methane completely.",
    morphology: "Greek 'stoicheion' (element) + '-metry' (measurement, as in geometry, telemetry).",
    synonyms: "",
    category: "chemistry",
  },
  {
    word: "Electronegativity",
    definition: "A measure of an atom's tendency to attract shared electrons in a bond.",
    context: "Oxygen's high electronegativity makes water polar — the basis of nearly all of its unusual properties.",
    morphology: "'electro-' (electron) + 'negativity' — pulls electrons toward its negative-charge-accumulating self.",
    synonyms: "electron affinity (related but distinct concept)",
    category: "chemistry",
  },
  {
    word: "Alloy",
    definition: "A mixture of metals, or a metal combined with another element, to enhance properties.",
    context: "Steel is an alloy of iron and carbon; bronze, of copper and tin.",
    morphology: "Latin 'alligare' (to bind to) — 'ad-' (to) + 'ligare' (bind), same root as 'ligament' and 'oblige'.",
    synonyms: "blend, amalgam (specifically with mercury)",
    category: "chemistry",
  },
  {
    word: "Oxidation state",
    definition: "The hypothetical charge an atom would have if all bonds were fully ionic.",
    context: "Iron's +2 and +3 oxidation states give rust its range of colors.",
    morphology: "'oxidation' from oxygen, the classic electron thief — though the concept no longer requires oxygen at all.",
    synonyms: "oxidation number",
    category: "chemistry",
  },
  {
    word: "Chelate",
    definition: "A compound where a ligand binds to a metal ion at two or more points, forming a ring.",
    context: "EDTA chelates lead in the bloodstream, which is why it's used to treat heavy-metal poisoning.",
    morphology: "Greek 'chele' (claw) — the ligand grips the metal like a crab's pincer.",
    synonyms: "complex (broader term)",
    category: "chemistry",
  },
  {
    word: "Phosphor",
    definition: "A substance that emits light (luminesces) when exposed to radiation.",
    context: "The white coating inside a fluorescent tube is a phosphor converting UV to visible light.",
    morphology: "Greek 'phos' (light) + 'phoros' (bearer) — light-bearer; same roots as 'photograph' and 'metaphor' (meta + phoros = carrying across).",
    synonyms: "luminophore",
    category: "chemistry",
  },
];
